name: gps_foto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  camera: ^0.10.0+5
  image_picker: ^0.8.4+3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
